name: CI Tests (Proxmox Self-Hosted)

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: guitare-ci:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer les dépendances du projet
        run: |
          pip install --no-build-isolation -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Exécuter Pytest
        run: pytest

      - name: Exécuter les tests JS
        run: node tests/js/resume.test.js
